name: Matrix deployment
on: push
jobs:
  build:
    strategy:
      matrix: 
        node-version: [12,14,16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{operating-system}}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: ${{node-version}}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build