name: Reusable deployment
# on: workflow_call
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: name of deployable artifact files 
        required: true
        default: dist
        type: string
    outputs:
      result:
        description: result of deploy operation
        value: 
jobs:
  deploy:
    outputs:
      outcome: ${{steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name}}  
      - name: list files
        run: ls
      - name: output info
        run: echo 'output info'
      - name: set result output
        id: set-result
        run: echo "::set-output name=step-result::success"
